src/gpu/ResourceCache.cpp

Fix the crash caused by pendingPurgeableResources potentially performing swap and push_back operations simultaneously.

Fix the crash caused by pendingPurgeableResources

---

src/codecs/png/PngCodec.cpp

If the PNG file is corrupted (but the file header is intact), tgfx will crash.
This pr complete the error handling in 'src/codecs/png/PngCodec.cpp'

Fix PNG decoder error handling

---

src/core/images/PictureImage.cpp
src/gpu/DrawingManager.cpp
src/gpu/DrawingManager.h
src/gpu/ProxyProvider.cpp
src/gpu/ProxyProvider.h
src/gpu/RenderContext.cpp
src/gpu/Surface.cpp
src/gpu/proxies/RenderTargetProxy.cpp
src/gpu/proxies/RenderTargetProxy.h
test/src/CanvasTest.cpp

整理了所有内部创建的 RenderTargetProxy 需要清屏的情况，统一改为使用 ProxyProvider 上的 clearAll 参数清屏。

Add the mssing clear op in the PictureImage class.

---

src/core/ImageFilter.cpp
src/core/filters/BlurImageFilter.cpp
src/core/images/Image.cpp
src/gpu/OpContext.cpp
src/gpu/OpContext.h
src/gpu/ProxyProvider.cpp
src/gpu/RenderTarget.h
src/gpu/opengl/GLRenderTarget.cpp
src/gpu/tasks/RenderTargetCreateTask.cpp
src/gpu/tasks/RenderTargetCreateTask.h
test/src/CanvasTest.cpp

在创建RenderTarget的时候执行清屏，避免额外产生一个ClearOp。另外OpContext被Surface持有了，它的析构函数不应该存在访问context的情况。

Handle the clearAll flag in RenderTargetCreateTask instead of creating a ClearOp.

---

src/core/Font.cpp
src/core/ScalerContext.cpp

修复Font初始化时，全局ScalerContext可能为nullptr导致后续crash的问题

Fix the issue that ScalerContext might be nullptr during Font initialization.

---

include/tgfx/layers/DisplayList.h
src/layers/DisplayList.cpp
src/layers/ImageLayer.cpp
src/layers/ShapeLayer.cpp

1. DisplayList的render方法添加返回值
2. 修复ShapeLayer中Path和PathProvider同时为空导致的crash

Added a return value to the render method of DisplayList

---

web/src/core/scaler-context.ts

添加static方法判断浏览器是否能直接检测文字大小，防止不可见的文字多次进入离屏渲染

Fix the issue of time consumption when reading invisible characters on the web platform

---

include/tgfx/core/PathEffect.h
include/tgfx/core/Stroke.h
src/core/Canvas.cpp
src/core/GlyphRunList.cpp
src/core/Mask.cpp
src/core/PathEffect.cpp
src/core/Stroke.cpp
src/core/TrimPathEffect.cpp
src/core/TrimPathEffect.h
src/core/vectors/coregraphics/CGScalerContext.cpp
src/gpu/ResourceKey.cpp
src/gpu/ResourceKey.h
src/gpu/ops/TriangulatingPathOp.cpp
src/layers/ShapeLayer.cpp
test/src/FilterTest.cpp

Remove the PathEffect::MakeStroke() method and add a applyToPath() method to Stroke.

---

src/platform/android/NativeCodec.cpp

If we use `BitmapFactory` for image decoding on the Android platform and do not set `inPreferredColorSpace`, the decoded color space will remain unchanged. If the original image is in the Display P3 color space and is used directly as a texture, it may result in color deviation. so it is necessary to set `inPreferredColorSpace` to perform color space conversion (to sRGB).
Ref: https://developer.android.com/reference/kotlin/android/graphics/BitmapFactory.Options#inpreferredcolorspace

Fix image decoding color space issue on Android

---

include/tgfx/core/Mask.h
src/core/Mask.cpp
src/core/Rasterizer.cpp
src/core/Rasterizer.h
src/core/images/PictureImage.cpp
src/core/vectors/coregraphics/CGMask.cpp
src/core/vectors/coregraphics/CGMask.h
src/core/vectors/freetype/FTMask.cpp
src/core/vectors/freetype/FTMask.h
src/core/vectors/web/WebMask.cpp
src/core/vectors/web/WebMask.h
src/gpu/RenderContext.cpp
src/gpu/RenderContext.h

Allow disabling anti-aliasing when rasterizing paths and texts.

---

include/tgfx/core/ImageFilter.h
include/tgfx/layers/filters/InnerShadowFilter.h
src/core/filters/InnerShadowImageFilter.cpp
src/core/filters/InnerShadowImageFilter.h
src/layers/filters/InnerShadowFilter.cpp
test/baseline/version.json
test/src/FilterTest.cpp
test/src/LayerTest.cpp

Support InnerShadowFilter.

---

test/baseline/version.json
test/src/CanvasTest.cpp

Add shape unit test

---

include/tgfx/layers/Layer.h

Initialize maskOwner to nullptr in Layer class.

---

src/core/images/BufferImage.cpp
src/core/images/BufferImage.h
src/core/images/DecoderImage.cpp
src/core/images/DecoderImage.h
src/core/images/FlattenImage.cpp
src/core/images/FlattenImage.h
src/core/images/GeneratorImage.cpp
src/core/images/GeneratorImage.h
src/core/images/Image.cpp
src/core/images/MipmapImage.cpp
src/core/images/MipmapImage.h
src/core/images/OffscreenImage.cpp
src/core/images/OffscreenImage.h
src/core/images/ResourceImage.cpp
src/core/images/ResourceImage.h
src/core/images/TextureImage.cpp
src/core/images/TextureImage.h
src/gpu/DrawingManager.cpp
src/gpu/DrawingManager.h
src/gpu/ProxyProvider.cpp
src/gpu/ProxyProvider.h
src/gpu/TPArgs.h
src/gpu/tasks/RenderTargetCreateTask.cpp
src/gpu/tasks/RenderTargetCreateTask.h

重构了Image::lockTextureProxy()方法，允许先请求TextureProxy再设置UniqueKey，同时修复之前FilterImage没有处理TPArgs.uniqueKey导致缓存没有生效的问题。

Remove uniqueKey from TPArgs and fix caching issue with flattened FilterImage.

---

DEPS

Update tracy third party lib, Solve the compilation problem of OHOS

---

web/package.json

Specify the version number of gen-mapping. The latest version is not recommended for use.

---

include/tgfx/layers/Layer.h
include/tgfx/layers/ShapeLayer.h
include/tgfx/layers/layerstyles/BackgroundBlurStyle.h
include/tgfx/layers/layerstyles/DropShadowStyle.h
include/tgfx/layers/layerstyles/LayerStyle.h
src/layers/DrawArgs.h
src/layers/Layer.cpp
src/layers/ShapeLayer.cpp
src/layers/layerstyles/BackgroundBlurStyle.cpp
src/layers/layerstyles/DropShadowStyle.cpp
src/layers/layerstyles/LayerStyle.cpp
test/baseline/version.json
test/src/LayerTest.cpp

Add a LayerStyle for drawing background blur effects.

---

src/core/Canvas.cpp
src/gpu/DrawingManager.cpp
src/gpu/DrawingManager.h
src/gpu/Gpu.h
src/gpu/OpsCompositor.cpp
src/gpu/OpsCompositor.h
src/gpu/RenderContext.cpp
src/gpu/RenderContext.h
src/gpu/RenderPass.cpp
src/gpu/RenderPass.h
src/gpu/Surface.cpp
src/gpu/opengl/GLCaps.cpp
src/gpu/opengl/GLGpu.cpp
src/gpu/opengl/GLGpu.h
src/gpu/opengl/GLRenderPass.cpp
src/gpu/ops/SubTextureCopyOp.cpp
src/gpu/ops/SubTextureCopyOp.h
src/gpu/tasks/RenderTargetCopyTask.cpp
src/gpu/tasks/RenderTargetCopyTask.h
test/src/SurfaceTest.cpp

修复当Surface开启MSAA后，makeImageSnapshot()结果错误的问题。

Fix Surface::makeImageSnapshot() for surfaces with MSAA enabled.

---

include/tgfx/svg/SVGValue.h

Fix compilation error when getting SVG value

---

src/svg/SVGNodeConstructor.cpp

fix compile error in SVG

---

include/tgfx/core/Picture.h
src/core/Canvas.cpp
src/core/Picture.cpp
src/core/Recorder.cpp
src/core/RecordingContext.cpp
src/core/RecordingContext.h
src/core/Records.h
src/core/TransformContext.cpp
src/core/TransformContext.h
src/core/images/PictureImage.cpp
src/core/utils/BlockBuffer.cpp
src/core/utils/BlockBuffer.h
src/layers/Layer.cpp
test/src/CanvasTest.cpp

使用BlockBuffer集中分配Picture的内存，并去掉重复的MCState和Fill的记录。

Improve picture recorder performance by using BlockBuffer for memory allocation.

---

src/core/utils/BlockBuffer.h
src/core/utils/PlacementArray.h
src/core/utils/PlacementPtr.h
src/gpu/DrawingManager.cpp
src/gpu/DrawingManager.h
src/gpu/OpsCompositor.cpp
src/gpu/ProxyProvider.cpp
src/gpu/ProxyProvider.h
src/gpu/RRectsVertexProvider.cpp
src/gpu/RRectsVertexProvider.h
src/gpu/RectsVertexProvider.cpp
src/gpu/RectsVertexProvider.h
src/gpu/VertexProvider.h
src/gpu/opengl/processors/GLQuadPerEdgeAAGeometryProcessor.cpp
src/gpu/opengl/processors/GLQuadPerEdgeAAGeometryProcessor.h
src/gpu/ops/ClearOp.h
src/gpu/ops/DstTextureCopyOp.h
src/gpu/ops/RRectDrawOp.cpp
src/gpu/ops/RRectDrawOp.h
src/gpu/ops/RectDrawOp.cpp
src/gpu/ops/RectDrawOp.h
src/gpu/ops/ResolveOp.h
src/gpu/ops/ShapeDrawOp.h
src/gpu/processors/DefaultGeometryProcessor.cpp
src/gpu/processors/QuadPerEdgeAAGeometryProcessor.cpp
src/gpu/processors/QuadPerEdgeAAGeometryProcessor.h
src/gpu/tasks/OpsRenderTask.h

1.允许QuadPerEdgeAAGeometryProcessor传递uvMatrix
2.从RectDrawOp和RRectDrawOp拆解出顶点数据相关的类RectsVertexProvider和RRectsVertexProvider
3.增加一个PlacementArray数组类存储PlacementPtr指针列表。

Pass uvMatrix to QuadPerEdgeAAGeometryProcessor and use a PlacementArray to store PlacementPtrs.

---

src/svg/SVGAttributeParser.cpp
src/svg/SVGAttributeParser.h
src/svg/SVGNodeConstructor.cpp

修复SVG文本解析器构造函数中，以临时字符串的初始化char指针成员变量（实际这个字符串对象立即会析构）。

Fixed in the SVGAttributeParser constructor where a temporary string was being assigned to a char pointer member variable.

---

web/demo/CMakeLists.txt
web/demo/index-st.html
web/demo/index-st.ts
web/demo/index.html
web/demo/index.ts

1、emsdk version < 4.0.4，禁用import.meta
2、4.0.4 <= emsdk version < 4.0.6，cmake构建报错，提示用户升级至4.0.6及更高版本
3、emsdk sdk >= 4.0.6，默认启用import.meta，多线程加载.js时指定加载路径

Enable compatibility with the latest version of Emscripten

---

include/tgfx/svg/SVGDOM.h
src/svg/SVGDOM.cpp
test/baseline/version.json
test/src/SVGRenderTest.cpp

改进获取SVG渲染区域大小的方法，如果没有设置就返回根节点的大小。
以提供给用户来获取合适的渲染区域大小。

Improve the method for determining the size of the rendered SVG.

---

include/tgfx/core/Matrix.h
include/tgfx/layers/Layer.h
src/core/GlyphRunList.cpp
src/core/Matrix.cpp
src/gpu/RenderContext.cpp
src/layers/Layer.cpp
src/svg/SVGExportContext.cpp

1、修改layer代码，当_rasterizationScale为0时，采用canvas中的scale。
2、将matrix中getmaxscale和getminscale返回的无效值从-1改为0。

If the _rasterizationScale equals zero, the layer will automatically apply adaptive scaling using the Canvas scale value.

---

src/gpu/OpsCompositor.cpp
test/baseline/version.json
test/src/LayerTest.cpp

1.解决由于web端和其他平台rt origin不一致，计算uvMatrix错误导致的frame_clip错误

Fix the issue where the canvas clip result is incorrect on a bottom-left surface

---

test/src/LayerTest.cpp

1、修改DecomposeRectTest测试中dirtyRect数量不正确导致的崩溃问题

Fix the crash caused by the DecomposeRectTest test in LayerTest.

---

src/core/PathRasterizer.h
src/core/vectors/coregraphics/CGPathRasterizer.cpp
src/core/vectors/freetype/FTPathRasterizer.cpp
src/core/vectors/web/WebPathRasterizer.cpp

增加可以自定义宽高的PathRasterizer::Make API , 因此path再绘制可以实现裁剪功能

Add a PathRasterizer::Make API with customizable width and height to  to support path render clipping.

---

include/tgfx/core/Stroke.h
src/core/Font.cpp
src/core/GlyphRasterizer.h
src/core/MeasureContext.cpp
src/core/Stroke.cpp
src/core/shapes/StrokeShape.cpp
src/core/utils/ApplyStrokeToBound.h
src/core/utils/StrokeUtils.cpp
src/gpu/RenderContext.cpp
test/baseline/version.json

1、将stroke的applyToBound函数从公开目录移动到私有目录

Remove the applyToBound() method of Stroke from the public APIs.

---

src/gpu/DrawingManager.cpp
test/baseline/version.json
test/src/LayerTest.cpp

DrawingManager::addResourceTask存在已有的ResourceTask时，跳过之前的，创建新的ResourceTask。

Fix an issue where a second ResourceTask with the same UniqueKey is not started in DrawingManager::addResourceTask().

---

include/tgfx/core/Image.h
include/tgfx/core/ImageBuffer.h
include/tgfx/core/ImageCodec.h
include/tgfx/core/ImageGenerator.h
src/core/GlyphRasterizer.cpp
src/core/ImageBuffer.cpp
src/core/PathRasterizer.cpp
src/core/PixelBuffer.h
src/core/RawPixelCodec.cpp
src/core/RawPixelCodec.h
src/core/images/CodecImage.cpp
src/core/images/CodecImage.h
src/core/images/GeneratorImage.cpp
src/core/images/Image.cpp
src/gpu/ops/AtlasTextOp.h
src/platform/web/NativeCodec.cpp
src/svg/SVGExportContext.cpp

1. 取消从外部像素数据创建 ImageBuffer 的 MakeFrom 方法，移动到 ImageCodec 上。
2. 给 ImageGenerator 添加 isImageCodec 的标志。
3. 给 ImageBuffer 添加 isPixelBuffer 的标志。

Move the MakeFrom() method for wrapping existing pixel data from ImageBuffer to ImageCodec.

---

src/core/Canvas.cpp
src/core/shapes/InverseShape.cpp
src/core/shapes/StrokeShape.cpp
src/core/shapes/StrokeShape.h

取消StrokeShape的useOwnUniqueKey属性，让外部创建的多个描边Shape也可以根据相同源Shape命中相同缓存。

Remove the useOwnUniqueKey parameter from StrokeShape to maximize cache reuse.

---

README.md
web/demo/CMakeLists.txt
web/demo/index-st.html
web/demo/index.html
web/script/rollup.demo.js
web/script/rollup.dev.js
web/script/rollup.tgfx.js

1、使用emsdk编译web时默认开启import.meta，并针对import.meta做兼容性适配
2、添加emsdk版本检查，遇到不支持的版本时结束构建
3、更新README.md，编译多线程web版本时添加用户说明

Support more emsdk versions

---

src/core/images/FilterImage.h
src/svg/ElementWriter.cpp
src/svg/ElementWriter.h
src/svg/SVGExportContext.cpp
test/baseline/version.json
test/src/SVGExportTest.cpp

先将FilterImage、PictureImage等分解然后再导出为SVG，而不是将Image直接以位图导出为SVG元素。

Fix the issue of exporting FilterImage and PictureImage as bitmaps in SVGs instead of as SVG elements.

---

src/core/utils/ShapeUtils.cpp
src/core/utils/ShapeUtils.h
src/gpu/OpsCompositor.cpp
test/baseline/version.json

以Hairline渲染极细的描边按线宽降低透明度。
拆解Shape计算当前渲染的描边宽度。

Reduce alpha for extremely thin strokes rendered as hairlines.

---

src/gpu/GPU.h
src/gpu/ProgramInfo.h
src/gpu/RenderPass.h
src/gpu/RenderPipeline.cpp
src/gpu/RenderPipeline.h
src/gpu/ShaderModule.h
src/gpu/glsl/GLSLProgramBuilder.cpp
src/gpu/opengl/GLGPU.cpp
src/gpu/opengl/GLGPU.h
src/gpu/opengl/GLRenderPass.cpp
src/gpu/opengl/GLRenderPass.h
src/gpu/opengl/GLRenderPipeline.cpp
src/gpu/opengl/GLRenderPipeline.h
src/gpu/opengl/GLShaderModule.h
src/gpu/resources/PipelineProgram.h
src/gpu/resources/Program.h

去掉几个类的GPU命名前缀，因为现在统一使用了智能指针管理对象，不需要显式靠GPU前缀来区分哪些是需要手动管理的GPU对象了。

Rename GPURenderPipeline to RenderPipeline and GPUShaderModule to ShaderModule.
